apiVersion: tekton.dev/v1
kind: Pipeline
metadata:

  labels:
    app.kubernetes.io/instance: app-dotnet
    app.kubernetes.io/name: app-dotnet
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/runtime: dotnet
    pipeline.openshift.io/runtime-version: 8.0-ubi8
    pipeline.openshift.io/type: kubernetes
  managedFields:
    - apiVersion: tekton.dev/v1

  name: app-dotnet
  namespace: mashraf-dev

spec:
  params:
    - default: app-dotnet
      name: APP_NAME
      type: string
    - default: 'https://github.com/bilal-rh/basic-dotnet-cicd.git'
      name: GIT_REPO
      type: string
    - default: 'main'
      name: GIT_REVISION
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/mashraf-dev/app-dotnet'
      name: IMAGE_NAME
      type: string
    - default: 'app-dotnet'
      name: PATH_CONTEXT
      type: string
    - default: 8.0-ubi8
      name: VERSION
      type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-dotnet
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc apply -f ../cicd/deploy
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace

# ---
# apiVersion: tekton.dev/v1beta1
# kind: Task
# metadata:
#   name: simple-publish
# spec:
#   resources:
#     inputs:
#       - name: source
#         type: git
#   steps:
#     - name: simple-dotnet-publish
#       image: registry.access.redhat.com/ubi8/dotnet-80:8.0-9 # .NET 8 SDK
#       securityContext:
#         runAsUser: 0  # UBI 8 images generally run as non-root
#       script: |
#           #!/usr/bin/bash
#           dotnet --info
#           cd source
#           dotnet publish -c Release -r linux-x64 --self-contained false "mvc_runtime_example.csproj"