apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-dotnet
  name: app-dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-dotnet
  template:
    metadata:
      labels:
        app: app-dotnet
    spec:
      containers:
      #todo: - pass project/ns and app name as argumement
        - image: image-registry.openshift-image-registry.svc:5000/mashraf-dev/mydotnet
          imagePullPolicy: Always
          name: app-dotnet
          ports:
            - containerPort: 8080
              protocol: TCP
